# Analysis of End of Season Rankings

In [37]:
import numpy as np
import pandas as pd
from bs4 import BeautifulSoup as bs
import matplotlib.pyplot as plt
import random

In [53]:
df = pd.read_csv('./data/ultimate/archives/open_college_archive_scraped.csv')
df.head()

         season  Rank                      Team      PR   W  L
0  1987_college     1                 Chabot CC  1961.0  11  0
1  1987_college     2  California-Santa Barbara  1854.0  12  1
2  1987_college     3                   Cornell  1807.0  27  4
3  1987_college     4              Cal Poly-SLO  1766.0  11  6
4  1987_college     5         SW Missouri State  1704.0  11  2

In [82]:
top20 = df[df['Rank']<=20]
pd.pivot_table(top20,index='Team',columns='season',values='PR',fill_value=0)

season,1987_college,1989_college,1990_college,1991_college,1992_college,1993_college,1994_college,1995_college,1996_college,1997_college,...,2010_college,2011_college,2012_college,2013_college,2014_college,2015_college,2016_college,2017_college,2018_college,2019_college
Team,,,,,,,,,,,,,,,,,,,,,
Arizona,0,0,0,0,1432,0,0,0,0,0,...,0,0,0,1808,0.0,0,0,0,0,0
Arizona State,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.0,1725,0,0,0,0
Auburn,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.0,0,1729,1766,1675,0
Boston College,0,0,0,1232,0,0,0,0,0,0,...,0,0,0,0,0.0,0,0,0,0,0
Brigham Young,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.0,0,1737,1851,1697,1896
British Columbia,0,0,0,0,0,0,0,0,1559,1742,...,1638,1688,0,0,0.0,0,1773,1804,0,0
Brown,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1811.5,0,0,0,1954,2181
Cal Poly-SLO,1766,1396,0,1278,1311,1296,0,1337,1435,1538,...,0,0,0,0,0.0,0,0,1745,1666,1956
California,0,1741,1258,1226,1475,1229,1420,0,0,1353,...,1786,0,1612,0,0.0,0,0,0,0,0
California-Davis,0,1372,1262,1249,0,0,0,1333,1339,1302,...,0,0,0,0,0.0,0,0,0,0,0
California-San Diego,0,0,0,0,0,1155,0,1211,1277,1512,...,0,0,0,0,1827.0,0,0,0,0,0
California-Santa Barbara,1854,1746,1597,1475,1363,1679,1730,1501,1776,1943,...,1727,0,0,0,0.0,0,0,0,0,0
California-Santa Cruz,0,1337,1488,1713,1349,1540,1576,1685,1244,1313,...,0,1641,0,0,0.0,0,0,0,0,0
Carleton College,0,0,1322,1315,1437,1538,1788,1435,1729,1542,...,1950,1983,1769,1932,0.0,1729,1865,2108,2165,0
Carleton College-CUT,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.0,0,0,0,0,1927
Carleton College-GOP,0,0,0,0,0,0,0,0,0,0,...,1577,0,0,0,0.0,0,0,0,0,0
Carnegie-Mellon,1540,1501,0,0,0,0,1308,1164,0,0,...,0,0,0,0,0.0,0,0,0,0,0
Central Florida,0,0,0,0,0,0,0,0,0,0,...,0,0,1648,1918,1842.9,1887,0,1698,0,1767
Chabot CC,1961,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.0,0,0,0,0,0
Chico State,0,1353,0,0,0,0,0,0,0,0,...,0,0,0,0,0.0,0,0,0,0,0
Cincinnati,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.0,1686,0,0,0,0
Colorado,0,0,0,0,0,0,0,0,0,1517,...,1708,1793,1655,1851,2094.6,1850,1897,1804,1676,1951
Colorado College,0,0,0,0,0,0,0,0,0,0,...,0,1598,0,0,0.0,0,0,0,0,0
Colorado State,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.0,0,0,0,0,0
Columbia,1617,1610,0,0,1226,0,0,0,0,0,...,0,0,0,0,0.0,0,0,0,0,0
Connecticut,0,0,0,0,0,0,0,0,0,0,...,0,0,1542,0,0.0,0,0,0,0,0
Cornell,1807,1338,1428,1371,1679,0,1654,1423,1458,1303,...,1720,0,0,0,0.0,0,0,0,0,0
Dartmouth,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1725,0.0,0,0,0,0,0
Davidson,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.0,0,0,0,0,0
Duke,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Pittsburgh,0,0,0,0,0,0,0,0,0,0,...,1824,1806,1852,2015,1933.1,1981,1952,2087,1957,1962
Princeton,1598,0,1255,0,0,0,0,0,0,0,...,0,0,0,0,0.0,0,0,0,0,0
Purdue,0,0,0,0,0,0,0,0,1210,0,...,0,0,0,0,0.0,0,0,0,0,0
Rice,0,0,0,0,0,0,0,0,0,1315,...,0,0,0,0,0.0,0,0,0,0,0
SUNY-Albany,0,0,1232,0,0,0,0,0,0,0,...,0,0,0,0,0.0,0,0,0,0,0
SUNY-Binghamton,1466,0,0,0,0,0,1299,1217,0,0,...,0,0,0,0,0.0,0,0,0,0,0
SUNY-Purchase,1636,0,1419,0,0,0,0,0,0,0,...,0,0,0,0,0.0,0,0,0,0,0
SW Missouri State,1704,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.0,0,0,0,0,0
Salisbury,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.0,0,0,0,0,0
San Diego State,0,0,0,0,0,0,0,0,0,0,...,0,1601,0,0,0.0,0,0,0,0,0
Southern California,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.0,0,0,0,0,1773
Stanford,1601,1793,1486,1413,1635,1584,2023,1546,1622,1865,...,0,0,1566,1733,0.0,0,1867,1800,0,0
Tennessee,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.0,0,0,0,0,0
Texas,1647,1799,0,0,1248,1562,0,0,0,0,...,0,1643,1588,1940,1960.8,1675,0,0,1743,1871
Texas A&M,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1732,1897.2,1837,1812,1736,0,0
Tufts,0,1473,1273,0,0,0,1282,0,0,0,...,1589,1614,1740,1799,1786.7,0,0,0,0,0
Tulane,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.0,1632,0,0,0,0
Vermont,1550,0,1435,1177,1287,0,0,0,0,0,...,0,0,0,0,0.0,0,0,0,0,0
Victoria,0,0,0,0,0,0,0,0,0,1490,...,0,0,0,0,0.0,0,0,0,0,0
Virginia,0,0,0,0,1226,1156,0,0,0,0,...,1645,1678,0,0,0.0,0,0,0,0,0
Virginia Tech,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.0,0,0,0,1702,0
Washington,0,0,0,0,0,0,0,0,0,0,...,0,1582,1578,0,0.0,1679,1708,1870,1870,1829
Wesleyan,1502,0,0,1331,1205,1209,0,1160,1267,0,...,0,0,0,0,0.0,0,0,0,0,0
Western Washington,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.0,0,0,0,0,0
Whitman,0,0,0,0,0,0,0,0,0,0,...,0,0,1550,1773,0.0,0,0,0,0,0
William & Mary,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.0,0,0,0,1679,0
Williams,0,0,0,0,0,0,0,1168,1237,0,...,0,0,0,0,0.0,0,0,0,0,0
Wisconsin,0,0,1294,1196,0,1344,1446,0,1597,1562,...,1754,1758,1786,2077,1803.7,1728,1961,1933,1764,1860
Wisconsin-Whitewater,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.0,0,0,0,0,0
Yale,0,0,0,0,0,0,0,1468,0,0,...,0,0,0,0,0.0,0,0,0,0,0

In [78]:
schools = ['British Columbia','Brown','California-Santa Barbara','Cal Poly-SLO','Carleton College','Colorado','Florida','Georgia','Harvard','Iowa','Iowa State','Marquette','Massachusetts','Michigan','Minnesota','North Carolina','North Carolina-Wilmington','North Carolina State','Oregon','Pittsburgh','Purdue','Stanford','Texas','Texas A&M','Washington','Wisconsin','Wisconsin-Whitewater']
pd.pivot_table(df[df['Team'].isin(schools)],index='Team',columns='season',values='PR',fill_value=0)

season,1987_college,1989_college,1990_college,1991_college,1992_college,1993_college,1994_college,1995_college,1996_college,1997_college,...,2010_college,2011_college,2012_college,2013_college,2014_college,2015_college,2016_college,2017_college,2018_college,2019_college
Team,,,,,,,,,,,,,,,,,,,,,
British Columbia,0,0,0,0,0,0,0,0,1559,1742,...,1638,1688,1342,0,1719.7,1535.0,1773,1804,1470,1430
Brown,1106,1152,932,0,942,384,772,621,1096,1120,...,1412,1132,1225,1601,1811.5,1405.0,1511,1593,1954,2181
Cal Poly-SLO,1766,1396,1165,1278,1311,1296,1027,1337,1435,1538,...,1116,1384,1475,885,1190.9,1333.0,1676,1745,1666,1956
California-Santa Barbara,1854,1746,1597,1475,1363,1679,1730,1501,1776,1943,...,1727,1391,1383,1366,1539.9,1612.0,1604,1532,1253,1451
Carleton College,1227,1254,1322,1315,1437,1538,1788,1435,1729,1542,...,1950,1983,1769,1932,1539.0,1729.0,1865,2108,2165,0
Colorado,999,0,917,0,0,1058,869,806,1162,1517,...,1708,1793,1655,1851,2094.6,1850.0,1897,1804,1676,1951
Florida,0,1371,0,0,0,0,0,0,0,1088,...,1993,1631,1480,1825,1844.8,1727.0,1827,1573,1752,1453
Georgia,1016,0,1197,1158,1209,1170,1565,1062,1372,1224,...,1613,1396,1499,1650,1513.3,1722.0,1866,1790,1790,1803
Harvard,0,916,1172,1154,1289,588,444,787,1010,1168,...,1730,1661,1430,1849,1884.2,1550.0,1838,1590,1425,1477
Iowa,0,0,0,0,965,1196,1320,922,817,1239,...,1687,1755,1692,1407,1420.5,1461.0,1449,1323,1582,1336
Iowa State,0,0,0,0,0,885,721,1117,753,0,...,1461,1252,1230,1228,1539.7,1401.0,1392,1524,1358,1630
Marquette,0,0,0,0,0,0,0,0,0,0,...,1104,0,1052,828,685.8,979.0,1035,1200,1489,1210
Massachusetts,1371,1045,890,614,901,520,510,741,752,1047,...,1451,1255,1285,1486,1780.4,1876.0,2067,2105,1867,1875
Michigan,1460,1395,0,0,730,907,1017,918,802,1079,...,1633,1589,1616,1597,1803.4,1602.0,1733,1839,1540,1746
Minnesota,1107,0,702,0,962,0,0,0,779,644,...,1728,1661,1674,2032,1877.5,1729.0,2007,1974,1860,1815
North Carolina,0,0,0,0,0,0,411,0,893,972,...,1515,1129,1600,2045,2071.3,1947.0,1831,2058,2140,2169
North Carolina State,983,888,396,0,0,957,1219,1318,1599,1338,...,1492,1051,1268,1261,1630.5,1501.0,1463,1769,1660,1816
North Carolina-Wilmington,963,1478,1588,1623,1617,1710,1313,1597,1570,1426,...,1707,1419,1505,1789,1849.2,1867.0,1910,1967,1694,1637
Oregon,1518,1484,1290,0,1734,1391,1442,989,955,1158,...,1699,1737,1829,2017,1898.8,1872.0,1956,1931,1996,1964
Pittsburgh,0,0,0,0,0,0,0,0,0,0,...,1824,1806,1852,2015,1933.1,1981.0,1952,2087,1957,1962
Purdue,968,762,0,0,561,986,1209,834,1210,713,...,1417,1166,1233,1031,0.0,738.5,1524,1577,1280,1468
Stanford,1601,1793,1486,1413,1635,1584,2023,1546,1622,1865,...,1416,1518,1566,1733,1690.0,1581.0,1867,1800,1612,1519
Texas,1647,1799,1086,0,1248,1562,1258,997,1078,839,...,1315,1643,1588,1940,1960.8,1675.0,1663,1557,1743,1871
Texas A&M,998,0,0,0,0,0,392,709,551,735,...,1158,0,1512,1732,1897.2,1837.0,1812,1736,1648,1623
Washington,0,1217,0,0,0,0,298,0,786,1101,...,1469,1582,1578,1545,1654.0,1679.0,1708,1870,1870,1829
Wisconsin,1393,1185,1294,1196,1190,1344,1446,1128,1597,1562,...,1754,1758,1786,2077,1803.7,1728.0,1961,1933,1764,1860
Wisconsin-Whitewater,0,0,0,0,0,0,0,0,0,0,...,1428,1464,932,0,703.4,1089.0,1116,1280,1242,1169

In [79]:
nc_region = ['Carleton College','Iowa','Iowa State','Marquette','Minnesota','Minnesota-Duluth','Wisconsin','Wisconsin-Milwaukee','Wisconsin-Whitewater']
pd.pivot_table(df[df['Team'].isin(nc_region)],index='Team',columns='season',values='PR',fill_value=0)

season,1987_college,1989_college,1990_college,1991_college,1992_college,1993_college,1994_college,1995_college,1996_college,1997_college,...,2010_college,2011_college,2012_college,2013_college,2014_college,2015_college,2016_college,2017_college,2018_college,2019_college
Team,,,,,,,,,,,,,,,,,,,,,
Carleton College,1227,1254,1322,1315,1437,1538,1788,1435,1729,1542,...,1950,1983,1769,1932,1539.0,1729,1865,2108,2165,0
Iowa,0,0,0,0,965,1196,1320,922,817,1239,...,1687,1755,1692,1407,1420.5,1461,1449,1323,1582,1336
Iowa State,0,0,0,0,0,885,721,1117,753,0,...,1461,1252,1230,1228,1539.7,1401,1392,1524,1358,1630
Marquette,0,0,0,0,0,0,0,0,0,0,...,1104,0,1052,828,685.8,979,1035,1200,1489,1210
Minnesota,1107,0,702,0,962,0,0,0,779,644,...,1728,1661,1674,2032,1877.5,1729,2007,1974,1860,1815
Minnesota-Duluth,975,0,0,0,0,0,0,0,0,0,...,1239,1342,1307,1328,1588.7,1327,1215,1382,1333,1165
Wisconsin,1393,1185,1294,1196,1190,1344,1446,1128,1597,1562,...,1754,1758,1786,2077,1803.7,1728,1961,1933,1764,1860
Wisconsin-Milwaukee,0,0,0,0,0,0,0,0,0,0,...,1305,1241,1385,1390,1569.4,1378,1416,1060,1117,1328
Wisconsin-Whitewater,0,0,0,0,0,0,0,0,0,0,...,1428,1464,932,0,703.4,1089,1116,1280,1242,1169

Looks like `Carleton College` doesn't have ranking info for 2019. This is probably because they changed their name to `Carleton College-CUT`.

In [81]:
df[df['Team']=='Carleton College-CUT']

            season  Rank                  Team      PR   W   L
8566  2019_college     7  Carleton College-CUT  1927.0  23  10

So let's adjust for that

In [85]:
df['Team'] = df['Team'].str.replace('Carleton College-CUT','Carleton College')
nc_region = ['Carleton College','Iowa','Iowa State','Marquette','Minnesota','Minnesota-Duluth','Wisconsin','Wisconsin-Milwaukee','Wisconsin-Whitewater']
pd.pivot_table(df[df['Team'].isin(nc_region)],index='Team',columns='season',values='PR',fill_value=0)

season,1987_college,1989_college,1990_college,1991_college,1992_college,1993_college,1994_college,1995_college,1996_college,1997_college,...,2010_college,2011_college,2012_college,2013_college,2014_college,2015_college,2016_college,2017_college,2018_college,2019_college
Team,,,,,,,,,,,,,,,,,,,,,
Carleton College,1227,1254,1322,1315,1437,1538,1788,1435,1729,1542,...,1950,1983,1769,1932,1539.0,1729,1865,2108,2165,1927
Iowa,0,0,0,0,965,1196,1320,922,817,1239,...,1687,1755,1692,1407,1420.5,1461,1449,1323,1582,1336
Iowa State,0,0,0,0,0,885,721,1117,753,0,...,1461,1252,1230,1228,1539.7,1401,1392,1524,1358,1630
Marquette,0,0,0,0,0,0,0,0,0,0,...,1104,0,1052,828,685.8,979,1035,1200,1489,1210
Minnesota,1107,0,702,0,962,0,0,0,779,644,...,1728,1661,1674,2032,1877.5,1729,2007,1974,1860,1815
Minnesota-Duluth,975,0,0,0,0,0,0,0,0,0,...,1239,1342,1307,1328,1588.7,1327,1215,1382,1333,1165
Wisconsin,1393,1185,1294,1196,1190,1344,1446,1128,1597,1562,...,1754,1758,1786,2077,1803.7,1728,1961,1933,1764,1860
Wisconsin-Milwaukee,0,0,0,0,0,0,0,0,0,0,...,1305,1241,1385,1390,1569.4,1378,1416,1060,1117,1328
Wisconsin-Whitewater,0,0,0,0,0,0,0,0,0,0,...,1428,1464,932,0,703.4,1089,1116,1280,1242,1169

Okay, that's way better. Now we're still missing data on other teams for seasons when they should have a Power Rating value. For example, check out `Wisconsin-Whitewater` for `2013_college` or `Marquette` for `2011_college`.