# Analysis of End of Season Rankings

In [1]:
import numpy as np
import pandas as pd
from bs4 import BeautifulSoup as bs
import matplotlib.pyplot as plt
import random

In [33]:
df = pd.read_csv('./data/ultimate/archives/open_college_archive_scraped.csv')
df.head()

         season  Rank                      Team    PR   W  L
0  1989_college     1                     Texas  1799   6  2
1  1989_college     2                  Stanford  1793  23  4
2  1989_college     3  California-Santa Barbara  1746  21  4
3  1989_college     4                California  1741  24  2
4  1989_college     5                  Columbia  1610  27  7

In [34]:
top20 = df[df['Rank']<20]
print(top20)

            season  Rank                       Team    PR   W   L
0     1989_college     1                      Texas  1799   6   2
1     1989_college     2                   Stanford  1793  23   4
2     1989_college     3   California-Santa Barbara  1746  21   4
3     1989_college     4                 California  1741  24   2
4     1989_college     5                   Columbia  1610  27   7
5     1989_college     6               Pennsylvania  1514  33   6
6     1989_college     7            Carnegie-Mellon  1501  13   5
7     1989_college     8                     Oregon  1484   6   4
8     1989_college     9  North Carolina-Wilmington  1478  19   3
9     1989_college    10              East Carolina  1477  18   5
10    1989_college    11                      Tufts  1473  20   8
11    1989_college    12                     Kansas  1405  12   6
12    1989_college    13               Cal Poly-SLO  1396   7   7
13    1989_college    14                   Michigan  1395  11   3
14    1989_college    15           California-Davis  1372   7   9
15    1989_college    16                    Florida  1371   8   6
16    1989_college    17                Chico State  1353   6   7
17    1989_college    17                    Indiana  1353  14   5
18    1989_college    19                    Cornell  1338   9   6
90    1990_college     1   California-Santa Barbara  1597  20   6
91    1990_college     2  North Carolina-Wilmington  1588  19   4
92    1990_college     3      California-Santa Cruz  1488  17   7
93    1990_college     4                   Stanford  1486  17   5
94    1990_college     5                    Vermont  1435  27   7
95    1990_college     6                    Cornell  1428  16   8
96    1990_college     7              SUNY-Purchase  1419  40   5
97    1990_college     8                Las Positas  1414  17   6
98    1990_college     9             Humboldt State  1375   4   5
99    1990_college    10           Carleton College  1322  20   6
100   1990_college    11                  Wisconsin  1294  26   5
...            ...   ...                        ...   ...  ..  ..
5682  2012_college     9            Central Florida  1648  34   8
5683  2012_college    10                   Michigan  1616  23  10
5684  2012_college    11                 California  1612  30  13
5685  2012_college    12             North Carolina  1600  30  12
5686  2012_college    13                     Luther  1594  22  15
5687  2012_college    14                      Texas  1588  25  11
5688  2012_college    15                 Washington  1578  29  12
5689  2012_college    16                   Stanford  1566  21   8
5690  2012_college    17                    Whitman  1550  14   9
5691  2012_college    18                Connecticut  1542  32   6
5692  2012_college    19                   Illinois  1530  21  10
6045  2013_college     1                  Wisconsin  2077  16   3
6046  2013_college     2             North Carolina  2045  20   4
6047  2013_college     3                  Minnesota  2032  12   1
6048  2013_college     4                     Oregon  2017  15   3
6049  2013_college     5                 Pittsburgh  2015  15   5
6050  2013_college     6                      Texas  1940  16   6
6051  2013_college     7           Carleton College  1932  14   7
6052  2013_college     8              Florida State  1924  13   6
6053  2013_college     9            Central Florida  1918  18   9
6054  2013_college    10                   Colorado  1851  14   8
6055  2013_college    11                    Harvard  1849  17   5
6056  2013_college    12                       Ohio  1835  14   4
6057  2013_college    13                    Florida  1825  10   7
6058  2013_college    14                    Arizona  1808  21   6
6059  2013_college    15                      Tufts  1799  16   8
6060  2013_college    16  North Carolina-Wilmington  1789  18   8
6061  2013_college    17                    Whitman  1773   8   4
6062  2013_college    18                   Stanford  1733   6  10
6063  2013_college    19                Texas A & M  1732  12   8

[476 rows x 6 columns]

In [35]:
pvt = pd.pivot_table(df[df['Rank']<100],index='Team',columns='season',values='PR',fill_value=0)
print(pvt)

season                    1989_college  1990_college  1991_college  \
Team
Air Force                            0             0             0
Alabama                              0             0             0
Alabama-Birmingham                   0             0             0
Amherst                              0             0             0
Amherst Regional HS                  0             0             0
Appalachian State                    0             0             0
Arizona                              0             0             0
Arizona State                        0             0             0
Arkansas                             0             0             0
Auburn                               0             0             0
Azusa Pacific                        0             0             0
Ball State                         618           227             0
Bates                                0             0             0
Baylor                               0             0             0
Bentley                              0             0             0
Berry                                0             0             0
Birmingham-Southern                  0             0             0
Boston College                     855          1182          1232
Boston University                  623          1073             0
Bowdoin                              0             0             0
Brandeis                             0             0             0
Brigham Young                        0             0             0
British Columbia                     0             0             0
British Columbia-B                   0             0             0
Brown                             1152           932             0
Brown-B                              0             0             0
Bucknell                           806             0           807
Cal Poly-SLO                      1396          1165          1278
Cal State-Long Beach                 0             0             0
California                        1741          1258          1226
...                                ...           ...           ...
Vassar                             714           495           815
Vermont                           1243          1435          1177
Victoria                             0             0             0
Virginia                           680           949          1085
Virginia Tech                      876           628             0
Wake Forest                        667             0             0
Washington                        1217             0             0
Washington University                0             0             0
Washington-B                         0             0             0
Wesleyan                          1276          1132          1331
Western Kentucky                     0             0             0
Western Michigan                     0             0             0
Western Washington                   0             0             0
Westmont                             0             0             0
Wheaton (Illinois)                   0             0             0
Wheaton (Illinois)-B                 0             0             0
Whitman                              0             0             0
William & Mary                    1015          1103             0
Williams                           927           958             0
Winona State                       967           760             0
Wisconsin                         1185          1294          1196
Wisconsin-B                          0             0             0
Wisconsin-Eau Claire                 0             0             0
Wisconsin-Milwaukee                  0             0             0
Wisconsin-Steven's Point             0             0             0
Wisconsin-Whitewater                 0             0             0
Worcester Polytech                   0             0             0
Wyoming                              0             0             0
Yale                              1134           622           368
Yale-B                               0             0             0

season                    1992_college  1993_college  1994_college  \
Team
Air Force                            0             0             0
Alabama                            816          1066          1077
Alabama-Birmingham                   0             0             0
Amherst                              0           175           609
Amherst Regional HS                  0             0             0
Appalachian State                    0             0             0
Arizona                           1432             0             0
Arizona State                        0             0             0
Arkansas                             0             0             0
Auburn                               0           903           496
Azusa Pacific                        0             0             0
Ball State                         534          1087           793
Bates                                0             0           643
Baylor                               0             0             0
Bentley                              0             0             0
Berry                                0             0             0
Birmingham-Southern                  0             0             0
Boston College                    1006          1077          1115
Boston University                    0             0           469
Bowdoin                              0             0             0
Brandeis                             0             0           461
Brigham Young                        0             0             0
British Columbia                     0             0             0
British Columbia-B                   0             0             0
Brown                              942           384           772
Brown-B                              0             0             0
Bucknell                             0           337             0
Cal Poly-SLO                      1311          1296          1027
Cal State-Long Beach                 0             0             0
California                        1475          1229          1420
...                                ...           ...           ...
Vassar                             932           621           631
Vermont                           1287           991           582
Victoria                             0             0             0
Virginia                          1226          1156           987
Virginia Tech                        0           164           624
Wake Forest                          0             0             0
Washington                           0             0             0
Washington University                0             0             0
Washington-B                         0             0             0
Wesleyan                          1205          1209          1004
Western Kentucky                     0             0             0
Western Michigan                     0             0             0
Western Washington                   0             0             0
Westmont                             0             0             0
Wheaton (Illinois)                   0             0             0
Wheaton (Illinois)-B                 0             0             0
Whitman                              0             0             0
William & Mary                       0           813           873
Williams                             0           945           973
Winona State                         0           531             0
Wisconsin                         1190          1344          1446
Wisconsin-B                          0             0             0
Wisconsin-Eau Claire                 0             0             0
Wisconsin-Milwaukee                  0             0             0
Wisconsin-Steven's Point             0             0             0
Wisconsin-Whitewater                 0             0             0
Worcester Polytech                   0             0           475
Wyoming                              0             0           688
Yale                               557           823          1278
Yale-B                               0             0           468

season                    1995_college  1996_college  1997_college  \
Team
Air Force                            0             0           780
Alabama                            525           695             0
Alabama-Birmingham                 756             0             0
Amherst                            716           936           686
Amherst Regional HS                831           750           752
Appalachian State                  882          1164          1072
Arizona                              0             0             0
Arizona State                      691           820             0
Arkansas                             0             0             0
Auburn                               0             0             0
Azusa Pacific                        0             0             0
Ball State                         621             0             0
Bates                                0             0             0
Baylor                               0           592             0
Bentley                              0             0             0
Berry                                0             0             0
Birmingham-Southern                  0             0             0
Boston College                    1095          1019             0
Boston University                  658             0             0
Bowdoin                            506             0             0
Brandeis                           490             0             0
Brigham Young                        0             0             0
British Columbia                     0          1559          1742
British Columbia-B                   0             0             0
Brown                              621          1096          1120
Brown-B                              0             0             0
Bucknell                           731             0             0
Cal Poly-SLO                      1337          1435          1538
Cal State-Long Beach                 0             0             0
California                        1022          1094          1353
...                                ...           ...           ...
Vassar                             781           634             0
Vermont                            825           826           859
Victoria                             0             0          1490
Virginia                           762             0           721
Virginia Tech                        0           899           910
Wake Forest                          0             0             0
Washington                           0           786          1101
Washington University                0           644           699
Washington-B                         0             0             0
Wesleyan                          1160          1267          1232
Western Kentucky                     0             0             0
Western Michigan                     0             0             0
Western Washington                   0             0             0
Westmont                             0             0             0
Wheaton (Illinois)                   0             0             0
Wheaton (Illinois)-B                 0             0             0
Whitman                              0             0             0
William & Mary                     891           724           682
Williams                          1168          1237           870
Winona State                         0           759           735
Wisconsin                         1128          1597          1562
Wisconsin-B                          0             0             0
Wisconsin-Eau Claire                 0             0             0
Wisconsin-Milwaukee                  0             0             0
Wisconsin-Steven's Point             0             0             0
Wisconsin-Whitewater                 0             0             0
Worcester Polytech                   0             0             0
Wyoming                            559             0           854
Yale                              1468          1101          1157
Yale-B                             819             0             0

season                    1998_college      ...       2004_college  \
Team                                        ...
Air Force                          920      ...                  0
Alabama                              0      ...                  0
Alabama-Birmingham                   0      ...                  0
Amherst                            765      ...                925
Amherst Regional HS                916      ...                848
Appalachian State                    0      ...                  0
Arizona                            756      ...                789
Arizona State                        0      ...                  0
Arkansas                             0      ...                920
Auburn                               0      ...                  0
Azusa Pacific                        0      ...                  0
Ball State                           0      ...                  0
Bates                                0      ...                  0
Baylor                               0      ...                  0
Bentley                              0      ...                  0
Berry                                0      ...                  0
Birmingham-Southern                  0      ...                  0
Boston College                       0      ...                  0
Boston University                    0      ...                796
Bowdoin                              0      ...                  0
Brandeis                             0      ...                  0
Brigham Young                        0      ...                709
British Columbia                  1536      ...               1270
British Columbia-B                   0      ...                743
Brown                             1493      ...               1303
Brown-B                              0      ...                  0
Bucknell                           908      ...                857
Cal Poly-SLO                       901      ...                922
Cal State-Long Beach                 0      ...                  0
California                        1065      ...               1454
...                                ...      ...                ...
Vassar                             714      ...                  0
Vermont                            920      ...                  0
Victoria                          1211      ...                  0
Virginia                           908      ...               1135
Virginia Tech                      913      ...                  0
Wake Forest                          0      ...                806
Washington                        1337      ...               1182
Washington University              886      ...                794
Washington-B                       890      ...                  0
Wesleyan                           936      ...                877
Western Kentucky                     0      ...                  0
Western Michigan                     0      ...                  0
Western Washington                   0      ...                894
Westmont                             0      ...                  0
Wheaton (Illinois)                   0      ...                  0
Wheaton (Illinois)-B                 0      ...                  0
Whitman                              0      ...                923
William & Mary                     850      ...               1240
Williams                          1187      ...                  0
Winona State                      1030      ...                  0
Wisconsin                         1327      ...               1297
Wisconsin-B                          0      ...                  0
Wisconsin-Eau Claire                 0      ...                  0
Wisconsin-Milwaukee                  0      ...                  0
Wisconsin-Steven's Point             0      ...                  0
Wisconsin-Whitewater                 0      ...                737
Worcester Polytech                   0      ...                  0
Wyoming                            756      ...                  0
Yale                              1275      ...                782
Yale-B                               0      ...                  0

season                    2005_college  2006_college  2007_college  \
Team
Air Force                            0             0             0
Alabama                              0             0             0
Alabama-Birmingham                   0             0             0
Amherst                            992             0             0
Amherst Regional HS                  0             0             0
Appalachian State                    0             0             0
Arizona                           1092           948          1242
Arizona State                      859             0          1065
Arkansas                          1096          1027          1138
Auburn                               0          1011          1020
Azusa Pacific                        0             0          1046
Ball State                           0             0             0
Bates                                0             0             0
Baylor                               0             0             0
Bentley                              0             0             0
Berry                                0             0             0
Birmingham-Southern                  0             0          1025
Boston College                       0             0             0
Boston University                    0           872             0
Bowdoin                              0             0             0
Brandeis                             0             0             0
Brigham Young                      962           810          1158
British Columbia                  1404          1365          1454
British Columbia-B                   0             0             0
Brown                             1632           980          1400
Brown-B                            858             0             0
Bucknell                           852           912          1033
Cal Poly-SLO                      1088             0          1065
Cal State-Long Beach                 0             0             0
California                        1145          1131          1352
...                                ...           ...           ...
Vassar                               0             0             0
Vermont                              0             0          1069
Victoria                             0             0             0
Virginia                          1159           943             0
Virginia Tech                        0             0             0
Wake Forest                          0           832          1231
Washington                        1296           943          1299
Washington University             1107           984          1178
Washington-B                         0             0             0
Wesleyan                             0             0             0
Western Kentucky                     0             0             0
Western Michigan                     0             0             0
Western Washington                1033          1229          1333
Westmont                             0             0             0
Wheaton (Illinois)                   0             0             0
Wheaton (Illinois)-B              1006             0             0
Whitman                           1052           903          1017

In [36]:
marq = df[df['Team']=='Marquette']
pd.pivot_table(marq,index='Team',columns='season',values='PR',fill_value=0)

season,2001_college,2002_college,2004_college,2005_college,2006_college,2007_college,2008_college,2009_college,2010_college,2012_college,2013_college
Team,,,,,,,,,,,
Marquette,618,610,301,627,790,1162,1185,1174,1104,1052,828